REPLACE INTO `quest_template` (`ID`, `QuestType`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestInfoID`, `SuggestedGroupNum`, `TimeAllowed`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `RewardNextQuest`, `RewardXPDifficulty`, `RewardMoney`, `RewardBonusMoney`, `RewardDisplaySpell`, `RewardSpell`, `RewardHonor`, `RewardKillHonor`, `StartItem`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `POIContinent`, `POIx`, `POIy`, `POIPriority`, `LogTitle`, `LogDescription`, `QuestDescription`, `AreaDescription`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4` `VerifiedBuild`) VALUES
(/*  ID    */802038,
 /*  QuestType  */ 2,
 /*  QuestLevel  */ 80,
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestInfoID*/ 0,
 /*  SuggestedGroupNum  */ 0,
 /*  TimeAllowed  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  RewardNextQuest  */ 0,
 /*  RewardXPDifficulty   */70,
 /*  RewardMoney  */ 2000000,
 /*  RewardBonusMoney  */ 2000000,
 /*  RewardDisplaySpell   */ 0,
 /*  RewardSpell  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardKillHonor  */ 0,
 /*  StartItem  */ 0,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardIten    */ 0,
 /*  RewardItem2   */ 0,
 /*  RewardItem3   */ 0,
 /*  RewardItem4   */ 0,
 /*  RewardAmount1 */ 0,
 /*  RewardAmount2 */ 0,
 /*  RewardAmount3 */ 0,
 /*  RewardAmount4 */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5  */ 0,
 /*  RewardChoiceItemID6  */ 0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  POIContinent  */ 0,
 /*  POIx  */ 0,
 /*  POIy  */ 0,
 /*  POIPriority  */ 0,
 /*  LogTitle  */ 'Rueckkehr',
 /*  LogDescription  */  'Bringt Krasus den seidenen Anhaenger.',
 /*  QuestDescription   */ 'Hallo $N, bringt den seidenen Anhaenger zu Krasus zurueck. Er wird wissen was zu tun ist.',
 /*  AreaDescription   */  '',
 /*  QuestCompletionLog  */ 'Es ist Eure Sache was ihr tut.',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 700517,
 /*  RequiredItemId2  */ 0,
 /*  RequiredItemId3  */ 0,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 1,
 /*  RequiredItemCount2  */ 0,
 /*  RequiredItemCount3  */ 0,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */ '',
 1);